[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --cov=. --cov-report=term-missing --cov-config=.coveragerc
filterwarnings =
    ignore:.*WindowsSelectorEventLoopPolicy.*:DeprecationWarning
    ignore:.*asyncio.set_event_loop_policy.*:DeprecationWarning