# Generated by Django 5.2 on 2026-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('follow', 'Follow'), ('repost', 'Repost'), ('mention', 'Mention'), ('direct_message', 'Direct Message')], max_length=20),
        ),
    ]
